#!/usr/bin/env bash
# Script to configure HAProxy on lb-01 to load balance between web-01 and web-02

# Install HAProxy
sudo apt update
sudo apt install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 6327-web-01 34.229.78.231:80 check
    server 6327-web-02 3.91.78.42:80 check
EOL

# Restart HAProxy service
sudo systemctl restart haproxy
sudo systemctl enable haproxy
